
//mapas
export const DATOS_MAPA = "DATOS_MAPA"

//student
export const CARGA_ESTUDIANTE = "CARGA_ESTUDIANTE"
export const VERIFICA_REGISTRO = "VERIFICA_REGISTRO"
export const ELIMINA_ESTUDIANTES = "ELIMINA_ESTUDIANTES"
export const OBTINE_ESTUDIANTES = "OBTINE_ESTUDIANTES"

//instructor
export const VERIFICA_INSTRUCTOR = "VERIFICA_INSTRUCTOR"
export const INICIA_SESION = "INICIA_SESION" 
export const REGISTRA_INSTRUCTOR = "REGISTRA_INSTRUCTOR"
export const OBTIENE_INSTRUCTOR = "OBTIENE_INSTRUCTOR"
